apiVersion: v1
kind: Service
metadata:
  name: malware-scanner
  labels:
    team: yts-clients
spec:
  selector:
    name: malware-scanner
    serving: "true"
  ports:
    - port: 443
      name: https
      targetPort: 8443
